<?php

declare(strict_types=1);

namespace Hypervel\Tests\Scout\Fixtures\Models;

use Hypervel\Database\Eloquent\Model;
use Hypervel\Scout\Searchable;

/**
 * Test model whose embeddings are generated by the search engine.
 */
class SearchableModelWithNativeEmbedding extends Model
{
    use Searchable;

    protected array $fillable = ['id', 'name', 'embedding'];

    public bool $timestamps = false;

    /**
     * Get the index name for the model when searching.
     */
    public function searchableAs(): string
    {
        return 'table';
    }

    /**
     * Get the index name for the model when indexing.
     */
    public function indexableAs(): string
    {
        return 'table';
    }
}
